@protocol = http
@domain = localhost
@port = 3000
@baseURL = {{protocol}}://{{domain}}:{{port}}
@contentType = application/json

###
GET {{baseURL}}

###
GET {{baseURL}}/users

###
GET {{baseURL}}/users/ec54925e-4e72-4469-886e-a0123ebf1b11

###
GET {{baseURL}}/users/paginated-users?limit=2&offset=1
