@protocol = http
@domain = localhost
@port = 3000
@baseURL = {{protocol}}://{{domain}}:{{port}}
@contentType = application/json
@token =

###
GET {{baseURL}}

###
POST {{baseURL}}/users
Content-Type: {{contentType}}

{
    "username": "lfnd0",
    "name": "Luiz Fernando",
    "email": "luiz.fernando@mail.com",
    "password": "hAVyqXbNEPBLV3n"
}

###
POST {{baseURL}}/sign-in
Content-Type: {{contentType}}

{
    "username": "lfnd0",
    "password": "hAVyqXbNEPBLV3n"
}

###
GET {{baseURL}}/users/profile
Authorization: Bearer {{token}}

###
POST {{baseURL}}/tasks
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
    "title": "Study NestJS",
    "description": "Watch classes and develop an API with NestJS.",
    "status": "todo",
    "priority": "high",
    "start_at": "2024-08-27 18:00",
    "end_at": "2021-08-27 20:00"
}
